dbt_demo:
  outputs:
    dev:
      account: bajbpay-du76720
      database: raw
      password: dbtPassword123
      role: TRANSFORM
      schema: airbnb
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
